Updates/optimize user service
rohteemie/iGotha pull request #48
Opened 2024-12-31 21:57 UTC by rohteemie

2025-01-01 23:45 UTC, Adeleye080 requested changes
Please read the comments

2025-01-01 23:45 UTC, Adeleye080 commented on backend/helper/redis.util.js
> +      return data ? JSON.parse(data) : null;
What if the stored value is a string? You stated here that the retrieved value be parsed as JSON.
Also, note that redis_client has an inbuilt `get` method that performs similar function

2025-01-02 05:02 UTC, rohteemie commented on backend/helper/redis.util.js
> +      return data ? JSON.parse(data) : null;
1. If a stored value isn't a key-value pairs, then we may not be needing redis because the key-value is fundamental to how Redis work.

Using Redis to store a string is overkill as it is design to store more complex use cases as caching, session storage and pub/sub.

I believe the best use cases in storing strings should be Environmental variable or In-memory storage.

2. The In-built get, set and del function Are still used, just that they are encapsulated for modularity extensibility and the ability to remove/add Redis usage in the application if need be.

2025-01-02 08:55 UTC, Adeleye080 commented on backend/helper/redis.util.js
> +      return data ? JSON.parse(data) : null;
I understand. The reason for the concern is that userID strings are stored in Redis in real-time when the user is online to obtain the user socketID. SocketID changes each time a user connects, and it is critical to map the socket ID to the user ID to ensure that messages are always delivered and not lost.
I am saying that user ID strings are saved in Redis.

Anyway, I think the changes can be accepted, will use the redisUtils whenever a JSON object is needed to be retrieved.

2025-01-02 08:56 UTC, Adeleye080 commented
Changes approved.
Please resolve conflict for merge

2025-01-14 15:16 UTC, Adeleye080 commented
@rohteemie 
Could you please solve the conflict issue?

2025-01-14 15:18 UTC, Adeleye080 approved these changes

2025-01-14 15:18 UTC, merged